site_name: Info Search and Summarization Workflow Doc

theme:
  name: "material"

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- include-markdown
- mkdocstrings

nav:
- Home: index.md
- Code Reference: reference/